# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotofuenv < Formula
  desc "OpenTofu and Terraform version manager (inspired by tofuenv, written in Go)"
  homepage "https://github.com/tofuutils/gotofuenv"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tofuutils/gotofuenv/releases/download/v1.0.2/gotofuenv_1.0.2_darwin_arm64.zip"
      sha256 "c5c3c5ba7acfef5a01d3b3e4713c37b4f3ce278c815a095690225fdb03928c3e"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tofuutils/gotofuenv/releases/download/v1.0.2/gotofuenv_1.0.2_darwin_amd64.zip"
      sha256 "a9e8458a6fdb8179293f650353eab03b691aab2e2bf3a20ffe61a3d4df3b249a"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tofuutils/gotofuenv/releases/download/v1.0.2/gotofuenv_1.0.2_linux_arm64.zip"
      sha256 "10d1ea207955ccaf157eab383ed854d526e8dd610baacca2cdb0229625f24fd5"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tofuutils/gotofuenv/releases/download/v1.0.2/gotofuenv_1.0.2_linux_amd64.zip"
      sha256 "f7ae664232c64dcf869dc95fa06875677c61b745c44adf9f00ee80f5a7b086ce"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tofuutils/gotofuenv/releases/download/v1.0.2/gotofuenv_1.0.2_linux_arm.zip"
      sha256 "a5438c3c14d0d3d29d7cbbc74e3e542d6bfd373e864186b7e23754407d8cd317"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
  end
end
