# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tenv < Formula
  desc "OpenTofu and Terraform version manager (inspired by tofuenv, written in Go)"
  homepage "https://github.com/tofuutils/tenv"
  version "1.0.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tofuutils/tenv/releases/download/v1.0.9/tenv_v1.0.9_Darwin_arm64.tar.gz"
      sha256 "663454bbcd9a5b2775cfabaa598a7235da8a36866bcd5f495670078afaf18bda"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tofuutils/tenv/releases/download/v1.0.9/tenv_v1.0.9_Darwin_x86_64.tar.gz"
      sha256 "ce2fec3748852b0cf88dadfba9e61eab94935efc57cc5cc0b48ee4af43c21513"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tofu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tofuutils/tenv/releases/download/v1.0.9/tenv_v1.0.9_Linux_x86_64.tar.gz"
      sha256 "3785243737e05da829bed6e720742a14b3b08492af34632de76d93d862d5ad0b"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tofuutils/tenv/releases/download/v1.0.9/tenv_v1.0.9_Linux_armv6.tar.gz"
      sha256 "c6eda54c81106ef7cb431241638f851a14cb943ab4f03257e7b99bce20f49b79"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tofuutils/tenv/releases/download/v1.0.9/tenv_v1.0.9_Linux_arm64.tar.gz"
      sha256 "7aa1356aa0fd78ee9230f0fd756f6f2e73ba5b76226578e013e759e79cd822d1"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tofu"
      end
    end
  end
end
