# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tenv < Formula
  desc "OpenTofu and Terraform version manager (inspired by tofuenv, written in Go)"
  homepage "https://github.com/tofuutils/tenv"
  version "1.9.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tofuutils/tenv/releases/download/v1.9.1/tenv_v1.9.1_Darwin_x86_64.tar.gz"
      sha256 "bb7956158f5d503711162b884eb5f9500007f88facd827c2e07d971b44266eb7"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tofuutils/tenv/releases/download/v1.9.1/tenv_v1.9.1_Darwin_arm64.tar.gz"
      sha256 "13679031013f4cd2058b06921366e989fdf3aead7b35cb39ace57cdd5bca00fc"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tofuutils/tenv/releases/download/v1.9.1/tenv_v1.9.1_Linux_x86_64.tar.gz"
      sha256 "86ddd0c80646457ba2650758c6e26257c3aa4810564f31120e12ae598c572673"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tofuutils/tenv/releases/download/v1.9.1/tenv_v1.9.1_Linux_armv6.tar.gz"
      sha256 "2e938e6f3f7ae9ff48fae70635d068b77e321b96a244885667bacc97083a6698"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tofuutils/tenv/releases/download/v1.9.1/tenv_v1.9.1_Linux_arm64.tar.gz"
      sha256 "dcb3b871cd69dcebd4e3bcf707271908ed9049415174ca29960ede740b4a13b4"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
  end
end
