# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tenv < Formula
  desc "OpenTofu and Terraform version manager (inspired by tofuenv, written in Go)"
  homepage "https://github.com/tofuutils/tenv"
  version "1.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tofuutils/tenv/releases/download/v1.10.0/tenv_v1.10.0_Darwin_x86_64.tar.gz"
      sha256 "1d13852b56b762353a28173400000dbf708ae6d5d6473353d2c26ab6b10e45de"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tofuutils/tenv/releases/download/v1.10.0/tenv_v1.10.0_Darwin_arm64.tar.gz"
      sha256 "2db97de86f63c25c83791ac660b5076a5fa220aec254b5b92c96a4c7ee17340f"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tofuutils/tenv/releases/download/v1.10.0/tenv_v1.10.0_Linux_x86_64.tar.gz"
      sha256 "7ceb2eefbdf08fc7326118b685de7f3ff0c02eaa61f0ec61b4b49d6ab55e42db"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tofuutils/tenv/releases/download/v1.10.0/tenv_v1.10.0_Linux_armv6.tar.gz"
      sha256 "67092829df6c4829be06837f71fb7faedef0701bfc958d240611ef2be31abc49"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tofuutils/tenv/releases/download/v1.10.0/tenv_v1.10.0_Linux_arm64.tar.gz"
      sha256 "1868e60775a1c1f41b502930ac921cf1cce2c94e0d67f0b12db6eadbb7c7a56e"

      def install
        bin.install "tenv"
        bin.install "terraform"
        bin.install "terragrunt"
        bin.install "tf"
        bin.install "tofu"
      end
    end
  end
end
